name: shop_item_repository
description: "Shop item repository"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.8
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  google_sign_in: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  theme_provider: ^0.6.0
  bloc: ^8.1.4
  cloud_firestore: ^5.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
